### ISSUE TITLE
Consider renaming StringLiteral::raw to StringLiteral::value and StringLiteral::value to StringLiteral::decoded

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent#222] opened 2018-11-29 21:14 UTC
In line with my feedback from https://github.com/projectfluent/fluent.js/pull/310, I'd like to suggest that we rename the main field of the StringLiteral to `value` and keep the optimization we have as `value` today with a new name like `encoded` which we could then mark as "optional" for implementations to introduce.

This would allow us to maybe remove the `encoded` field from test fixtures since it's an optimization for the fluent.js, rather than part of the reference AST. (or mark that field as optional for tests to pass).

**Comment by stasm** [comment] 2018-11-30 15:40
(I moved this issue to the spec repo since it affects the reference parser.)

> In line with my feedback from https://github.com/projectfluent/fluent.js/pull/310, I'd like to suggest that we rename the main field of the StringLiteral to value and keep the optimization we have as value today with a new name like encoded which we could then mark as "optional" for implementations to introduce.

The current design, including naming, was based on https://github.com/projectfluent/fluent/issues/195#issuecomment-433862461. The goal of adding the unescaped value to the AST was to standardize how escape sequences are intended to work. Before, the expected behavior wasn't specified at all.

The escape sequences can be unescaped statically during parsing, which makes the AST more usable. For tooling, the `raw` field is available, too. I see both fields as essential parts of the reference parser.

> This would allow us to maybe remove the encoded field from test fixtures since it's an optimization for the fluent.js, rather than part of the reference AST. (or mark that field as optional for tests to pass).

I see a difference between the reference parser and the reference AST. As I think I mentioned before, I think the implementations should be free to use any AST they are most comfortable with, and are only required to be able to serialize it into a reference-compliant JSON structure.

**Comment by stasm** [comment] 2019-03-05 17:16
This was fixed by #243.

**Closed by stasm** 2019-03-05 17:16 UTC
