### ISSUE TITLE
Allow indention of SelectorExpression

### ISSUE THREAD

**Issue by Pike** [projectfluent/fluent#106] opened 2018-05-16 10:22 UTC
Should we allow this?

```
foo = {
  $count ->
    [0] none
   *[many] many
 }
```

Found while reviewing #103.

**Comment by stasm** [comment] 2018-05-16 11:41
Yes, that's the intent of the current EBNF. Should I fix this in #103?

**Comment by Pike** [comment] 2018-05-18 09:30
Actually, yes, rereading our current spec, that's a regression in #103.

**Comment by stasm** [comment] 2018-05-18 09:53
I wouldn't call it a regression :) The old EBNF only allows `__?` between the opening `{` of a placeable and the expression inside of it. This makes something as simple as `{ x }` invalid because `__` doesn't allow for inline space without a line break. So yeah, the old EBNF is broken and #103 fixes it in many ways.

I think that what we intended was to allow both inline whitespace and indented whitespace after the opening `{` in placeables.

As I mentioned in https://github.com/projectfluent/fluent/pull/103#issuecomment-389901269, doing it right now is not trivial. It's possible but it would delay #103. OTOH, #102 will likely solve this too, so I'd prefer to wait for it rather than try to fix this issue right now.

**Comment by stasm** [comment] 2018-08-01 09:02
I'm closing it in favor of #87 which will almost certainly fix this. Please re-open if I misunderstood the problem.

**Closed by stasm** 2018-08-01 09:02 UTC
Labels: forwards incompatible, spec: grammar
